"""Independent arithmetic and long homogeneous checks for CE-UR4-D4.

The 77 DOP853 traces are frozen references, not regenerated by the AVF solver.
The spatial energy audit expands F directly without using solver.energy/local.
"""
import argparse
from concurrent.futures import ProcessPoolExecutor, as_completed
import json
from pathlib import Path

import numpy as np
import ce_record_radiation as model
import ce_record_backreaction as base


def homogeneous():
    reference_path = Path(base.__file__).with_suffix('.json')
    reference = json.loads(reference_path.read_text(encoding='utf-8'))
    assert reference['source_hashes'][Path(base.__file__).name] == model.digest(base.__file__)
    results = []
    for c in reference['cases']:
        if c['eta'] != .1:
            continue
        assert c['numerical_gate_passed']
        mass = c['mass_over_V']
        z, _ = base.initial_state(mass, .1, c['theta'])
        t_ref, q_ref = np.array(c['trace']['tau']), np.array(c['trace']['qpower'])
        for dt in [.04, .02, .01]:
            y = np.r_[z[:5].real, z[:5].imag][None, :]
            v = np.r_[z[5:].real, z[5:].imag][None, :]
            trace = []
            e0 = model.energy(y, v, np.ones(1), np.zeros(0), mass, model.CUBIC).sum()
            drift = 0.
            for k in range(round(60/dt)+1):
                if k % round(.2/dt) == 0:
                    trace.append([k*dt, y[0, 4]**2+y[0, 9]**2])
                    drift = max(drift, abs(model.energy(y, v, np.ones(1), np.zeros(0), mass, model.CUBIC).sum()/e0-1))
                if k < round(60/dt):
                    y, v, _, _ = model.step(y, v, dt, np.ones(1), np.zeros(0), mass)
            tr = np.array(trace)
            rq = np.interp(tr[:, 0], t_ref, q_ref)
            results.append({'species': c['species'], 'theta': c['theta'], 'dt': dt,
                'duration': 60, 'comparison_spacing': .2,
                'Q_max_scaled_difference': float(np.max(np.abs(tr[:, 1]-rq)/np.maximum(1, np.abs(rq)))),
                'Q_max_absolute_difference': float(np.max(np.abs(tr[:, 1]-rq))),
                'energy_relative_residual': float(drift)})
    phase = []
    for dt in [.04, .02, .01]:
        for physical_mass in [1., 4., 5.]:
            omega = physical_mass/base.MREF
            modified = 2*np.arctan(omega*dt/2)/dt
            phase.append({'dt': dt, 'linear_heavy_mass_over_V': physical_mass,
                'true_frequency_tau': omega, 'AVF_linear_frequency_tau': modified,
                'relative_frequency_error': (modified-omega)/omega,
                'unwrapped_phase_error_at_tau80': 80*(modified-omega)})
    return {'chapter77_result_sha256': model.digest(reference_path), 'comparisons': results,
            'fine_Q_gate_pass': max(r['Q_max_scaled_difference'] for r in results if r['dt'] == .02) <= .005,
            'heavy_linear_phase_errors': phase,
            'heavy_phase_resolved': False,
            'phase_scope': 'Vacuum linearized oscillators; phase errors are not errors of the small full nonlinear heavy field.'}


def spatial(path):
    data = json.loads(path.read_text(encoding='utf-8'))
    for key, value in model.provenance().items():
        assert data[key] == value
    results = {}
    for name, run in data['runs'].items():
        dx, outer, mass = run['dx'], run['outer'], run['mass']
        edges = np.arange(round(outer/dx)+1)*dx
        volume = (edges[1:]**3-edges[:-1]**3)/3
        center = (edges[:-1]+edges[1:])/2
        k = edges[1:-1]**2/dx
        raw = np.array(run['final_fields_real10_velocity10'])
        field = base.AREF*(raw[:, :5]+1j*raw[:, 5:10])
        velocity = raw[:, 10:15]+1j*raw[:, 15:20]
        z, t, s, u, q = field.T
        a = 1/(2*np.sqrt(15))
        f = np.array([-z+a*z*z+3*a*t*t+a*s*s+3*a*u*u-3*a*q*q/2,
            -5*t+6*a*z*t+6*a*s*u-q*q/4,
            (mass+2*a*z)*s+6*a*t*u,
            (mass-4+6*a*z)*u+6*a*t*s,
            -(3*a*z+t/2)*q]).T
        cells = volume[:, None]*(np.abs(velocity)**2+np.abs(f/(base.AREF*base.MREF))**2)
        faces = k[:, None]*np.abs(np.diff(field/base.AREF, axis=0))**2
        cells[:-1] += faces/2
        cells[1:] += faces/2
        e0 = run['initial_energy_dimensionless_no_4pi']
        final = run['trace'][-1]
        outside = center >= 40
        core = center < run['radius']/4
        qc = 3/(run['radius']/4)**3*np.sum(volume[core]*np.abs(q[core]/base.AREF)**2)
        errors = {'energy_relative_residual': abs(cells.sum()/e0-1),
            'outside_fraction_error': abs(cells[outside].sum()/e0-final[2]),
            'Higgs_fraction_error': abs(cells[outside, 4].sum()/e0-final[3]),
            'Q_error': abs(qc-final[1]),
            'signed_flux_split_error': abs(run['outward_integrated_flux_over_E0']-run['inward_integrated_flux_over_E0']-final[4])}
        assert max(errors.values()) < 1e-6, (name, errors)
        results[name] = {k: float(v) for k, v in errors.items()}
    return {'result_sha256': model.digest(path), 'runs': results}


def refine(path, workers):
    """Halve dx and dt only for failed registered observable comparisons."""
    data = json.loads(path.read_text(encoding='utf-8'))
    for key, value in model.provenance().items():
        assert data[key] == value
    assert len(data['comparisons']) == 10 and 'outer_boundary_comparison' in data
    tasks = []
    for case in model.cases():
        comparison = data['comparisons'][case[0]]
        if comparison['observable_convergence_pass'] and comparison['energy_and_flux_pass'] and comparison['retention_agrees']:
            continue
        runs = [r for r in data['runs'].values() if r['case'] == case[0] and r['outer'] == 140 and r['duration'] == 80]
        fine = min(runs, key=lambda r: r['dx'])
        tasks.append((case, fine['dx']/2, fine['dt']/2, 140, 80))
    source_hash = model.digest(__file__)
    parent_hash = model.digest(path)
    print('Refining:', [t[0][0] for t in tasks], flush=True)
    with ProcessPoolExecutor(max_workers=workers) as pool:
        futures = {pool.submit(model.simulate, *t): t for t in tasks}
        for future in as_completed(futures):
            task, run = futures[future], future.result()
            key = f'{task[0][0]}_dx{task[1]:g}_dt{task[2]:g}_L140_T80'
            run['refinement_driver_sha256'] = source_hash
            run['pre_refinement_result_sha256'] = parent_hash
            data['runs'][key] = run
            relevant = sorted([r for r in data['runs'].values() if r['case'] == run['case'] and r['outer'] == 140 and r['duration'] == 80], key=lambda r: r['dx'], reverse=True)
            original = data['comparisons'][run['case']]
            data.setdefault('earlier_comparisons', {}).setdefault(run['case'], []).append(original)
            data['comparisons'][run['case']] = model.compare(relevant[-2], relevant[-1])
            model.save(data, path)
            print(json.dumps({'case': run['case'], 'dx': run['dx'], 'Q_peak': run['Q_peak'],
                'Q_late_min': run['Q_late_min'], 'elapsed_seconds': run['elapsed_seconds'],
                'comparison': data['comparisons'][run['case']]}), flush=True)


def figure(path):
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    data = json.loads(path.read_text(encoding='utf-8'))
    best = {}
    for r in data['runs'].values():
        if r['outer'] == 140 and r['duration'] == 80 and (r['case'] not in best or r['dx'] < best[r['case']]['dx']):
            best[r['case']] = r
    fig, axes = plt.subplots(2, 2, figsize=(11, 7.5), constrained_layout=True)
    colors = {'minus': '#1565c0', 'plus': '#c62828', 'empty': '#444444'}
    for species in ['minus', 'plus']:
        for phase in [0, 1]:
            run = best[f'{species}_R30_p{phase}']
            tr = np.array(run['trace'])
            axes[0, 0].plot(tr[:, 0], tr[:, 1], color=colors[species], ls='-' if phase == 0 else '--',
                label=f'm{chr(8722) if species == "minus" else "+"}, phase {"0" if phase == 0 else "pi/4"}')
        for radius in [10, 30]:
            run = best[f'{species}_R{radius}_p0']
            tr = np.array(run['trace'])
            axes[1, 0].plot(tr[:, 0], tr[:, 2], color=colors[species], ls='-' if radius == 30 else '--',
                label=f'{species}, R={radius}')
        run = best[f'{species}_R10_p0']
        tr = np.array(run['trace'])
        axes[0, 1].semilogy(tr[:, 0], np.maximum(tr[:, 1], 1e-18), color=colors[species], label=f'{species}, R=10')
        run = best[f'{species}_R30_p0']
        fields = np.array(run['final_fields_real10_velocity10'])
        x = (np.arange(len(fields))+.5)*run['dx']
        axes[1, 1].plot(x, fields[:, 4]**2+fields[:, 9]**2, color=colors[species], label=f'{species}, R=30')
    for radius, ls in [(10, ':'), (30, '-.')]:
        tr = np.array(best[f'empty_R{radius}']['trace'])
        axes[0, 1].semilogy(tr[:, 0], np.maximum(tr[:, 1], 1e-18), color=colors['empty'], ls=ls, label=f'empty, R={radius}')
    for ax in axes[0]:
        ax.axhline(1, color='#777777', lw=.8)
        ax.axvspan(70, 80, color='#dddddd', alpha=.35)
        ax.set(xlabel='Time tau', ylabel='Core pointer Qc', xlim=(0, 80))
    axes[0, 0].set_title('(a) R=30: survival in the registered window')
    axes[0, 1].set(title='(b) R=10 and empty-source controls', ylim=(1e-16, 2))
    axes[1, 0].set(title='(c) Energy outside x=40 (phase 0)', xlabel='Time tau', ylabel='E(out) / E(initial)', xlim=(0, 80))
    axes[1, 1].axvline(7.5, color='#777777', lw=.8, ls=':', label='R/4')
    axes[1, 1].axvline(40, color='#777777', lw=.8, ls='--', label='energy boundary')
    axes[1, 1].set(title='(d) Higgs profile at tau=80 (phase 0)', xlabel='Radius x', ylabel='|q / Aref| squared', xlim=(0, 85))
    for ax in axes.flat:
        ax.grid(alpha=.18)
        ax.legend(fontsize=8)
    fig.suptitle('CE-UR4-D4: supplied classical preparations, conserved exterior fields', fontsize=13)
    target = model.CHAPTER.with_name('78_record_radiation.svg')
    fig.savefig(target, metadata={'Date': None, 'Creator': 'ce_record_radiation_audit.py'})
    fig.savefig(target.with_suffix('.png'), dpi=160)
    plt.close(fig)
    return {'svg': str(target.relative_to(model.ROOT)), 'sha256': model.digest(target),
            'data_sha256': model.digest(path)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--homogeneous', action='store_true')
    parser.add_argument('--spatial', type=Path)
    parser.add_argument('--refine', type=Path)
    parser.add_argument('--workers', type=int, default=2)
    parser.add_argument('--figure', type=Path)
    args = parser.parse_args()
    path = Path(__file__).with_suffix('.json')
    result = {'scientific_success': False, 'full_joint_rmse': None, **model.provenance(),
              'audit_source_sha256': model.digest(__file__)}
    if path.exists() and not args.homogeneous:
        existing = json.loads(path.read_text(encoding='utf-8'))
        assert all(existing[k] == v for k, v in result.items())
        result = existing
    if args.homogeneous:
        result['full_action_embedding_checks'] = base.algebra_checks()
        result['long_homogeneous_comparison'] = homogeneous()
    if args.refine:
        refine(args.refine, args.workers)
    if args.spatial:
        result['spatial_independent_energy_audit'] = spatial(args.spatial)
    if args.figure:
        result['figure'] = figure(args.figure)
    if args.spatial:
        data = json.loads(args.spatial.read_text(encoding='utf-8'))
        complete = len(data['comparisons']) == 10 and 'outer_boundary_comparison' in data
        comparisons = list(data['comparisons'].values())+[data.get('outer_boundary_comparison', {})]
        passed = complete and all(c.get('observable_convergence_pass') and c.get('energy_and_flux_pass')
                                  and c.get('retention_agrees') for c in comparisons)
        result['registered_suite_complete'] = complete
        result['numerical_gate_passed'] = bool(passed and result.get('long_homogeneous_comparison', {}).get('fine_Q_gate_pass'))
        result['judgment_scope'] = 'Registered classical pointer and energy observables, tau <= 80; fast heavy phase unresolved.'
        result['retention_at_finest_grid'] = {}
        for case in model.cases():
            relevant = [r for r in data['runs'].values() if r['case'] == case[0] and r['outer'] == 140 and r['duration'] == 80]
            if relevant:
                run = min(relevant, key=lambda r: r['dx'])
                result['retention_at_finest_grid'][case[0]] = {k: run[k] for k in ['dx', 'dt', 'Q_peak', 'Q_peak_time',
                    'Q_late_min', 'Q_late_max', 'late_retention', 'up_crossings', 'down_crossings']}
    model.save(result, path)
    print(json.dumps({k: v for k, v in result.items() if k != 'spatial_independent_energy_audit'}), flush=True)
    if args.spatial:
        print('Independent energy audit runs:', len(result['spatial_independent_energy_audit']['runs']), flush=True)


if __name__ == '__main__':
    main()
