"""check_k3.py -- Q-0002 attempt-02, candidate K3 (constraint-level energy ledger), numpy only.

Pre-declared before running: SEED=20260902, TOL=1e-10 (agreement), SEP=1e-3 (separation).
Prints JSON {"claim":"K3","checks":{...},"all_pass":bool} to stdout and writes result.json
next to this script.

Model (Z_N group-averaging projector, no boundary):
  clocks C_i = C^N, H_i = diag(0..N-1) (labels mod N);
  S = R (x) Q, register qubit R (bare energy 0), flux qubit Q with n_Q = diag(0,1);
  constraint H = H_1 + H_2 + H_S, Z_N generated by U = exp(2 pi i H / N),
  Pi = (1/N) sum_n U^n = projector onto {k1 + k2 + eps_e = 0 mod N};
  reduction V_i(tau) = sqrt(N) <tau|_i restricted to H_phys : H_phys -> C_j (x) S (unitary);
  relational observable O^{(i)}_A(tau) = N Pi (|tau><tau|_i (x) A) Pi = B V_i^dag A V_i B^dag.

Configurations:
  A0: N=7,  E*=1, H_S = E* n_Q                                  (g=0, [P_b,H_S]=0)
  A2: N=7,  E*=1, H_S = E* n_Q + 2 sigma_x^R (x) n_Q            (task-literal g=2; eigenvalues 0,0,3,-1)
  B : N=13, E*=1, H_S = (E* + 3 sigma_x^R + 4 sigma_z^R) (x) n_Q (eigenvalues 0,0,6,-4; [D(H_S),H_S] != 0)
  E39: N=7, H_S' = E*(n_Q + 1 - n_R)                             (E39-B storage Hamiltonian, one-receipt)
  X : exact-kernel (attempt-01 style) N=7 with A2's H_S, for comparison only.
"""
from __future__ import annotations

import json
import os
import sys

import numpy as np

SEED = 20260902
TOL = 1e-10
SEP = 1e-3
N_STATES = 20
N_RANDOM_OPS = 20

I2 = np.eye(2, dtype=complex)
I4 = np.eye(4, dtype=complex)
SX = np.array([[0, 1], [1, 0]], dtype=complex)
SZ = np.array([[1, 0], [0, -1]], dtype=complex)
NQ = np.diag([0.0, 1.0]).astype(complex)
NR = np.diag([0.0, 1.0]).astype(complex)
# S index s = 2*r + q  (r register, q flux):  kron(R-operator, Q-operator)
P_REG = [np.kron(np.diag([1.0, 0.0]).astype(complex), I2), np.kron(np.diag([0.0, 1.0]).astype(complex), I2)]


def kron3(a, b, c):
    return np.kron(np.kron(a, b), c)


def opnorm(X):
    return float(np.linalg.norm(X, 2))


def comm(A, B):
    return A @ B - B @ A


def block_diag_part(HS):
    """D(H_S) = sum_b P_b H_S P_b (register-diagonal part)."""
    return sum(P @ HS @ P for P in P_REG)


def off_diag_part(HS):
    """sum_{b != b'} P_b H_S P_b'."""
    return P_REG[0] @ HS @ P_REG[1] + P_REG[1] @ HS @ P_REG[0]


class Model:
    """Kinematic space C^N (x) C^N (x) C^4, index ((k1)*N + k2)*4 + s."""

    def __init__(self, N: int, HS: np.ndarray, mode: str = "modN", clock_shift=(0, 0)):
        self.N, self.mode = N, mode
        IN = np.eye(N, dtype=complex)
        self.IN = IN
        if mode == "modN":
            base = np.arange(N)
        else:
            M = (N - 1) // 2
            base = np.arange(-M, M + 1)
        self.K1 = base + clock_shift[0]
        self.K2 = base + clock_shift[1]
        eps, W = np.linalg.eigh(HS)
        if np.max(np.abs(eps - np.round(eps))) > 1e-9:
            raise ValueError("H_S must have integer spectrum")
        self.eps = np.round(eps).astype(int)
        self.W = W
        self.HS = HS.astype(complex)
        D = N * N * 4
        self.D = D
        self.Wfull = kron3(IN, IN, W)
        lam = (self.K1[:, None, None] + self.K2[None, :, None] + self.eps[None, None, :]).reshape(D)
        self.lam = lam
        if mode == "modN":
            mask = (np.mod(lam, N) == 0)
        else:
            mask = (lam == 0)
        self.mask = mask
        self.B = self.Wfull[:, mask]
        self.d = int(mask.sum())
        self.Pi = self.B @ self.B.conj().T
        self.Hfull = kron3(np.diag(self.K1).astype(complex), IN, I4) + kron3(IN, np.diag(self.K2).astype(complex), I4) + kron3(IN, IN, self.HS)
        self.HjS = {1: np.kron(np.diag(self.K2).astype(complex), I4) + np.kron(IN, self.HS),
                    2: np.kron(np.diag(self.K1).astype(complex), I4) + np.kron(IN, self.HS)}

    # --- clock states -------------------------------------------------
    def clock_bra(self, i: int, tau: float) -> np.ndarray:
        ks = self.K1 if i == 1 else self.K2
        return np.exp(1j * ks * tau) / np.sqrt(self.N)

    def R(self, i: int, tau: float) -> np.ndarray:
        bra = self.clock_bra(i, tau)[None, :]
        if i == 1:
            return kron3(bra, self.IN, I4)
        return kron3(self.IN, bra, I4)

    def V(self, i: int, tau: float) -> np.ndarray:
        return np.sqrt(self.N) * self.R(i, tau) @ self.B  # 4N x d

    # --- group averaging -----------------------------------------------
    def U(self) -> np.ndarray:
        phase = np.exp(2j * np.pi * self.lam / self.N)
        return self.Wfull @ np.diag(phase) @ self.Wfull.conj().T

    def Pi_group_average(self) -> np.ndarray:
        U = self.U()
        acc = np.eye(self.D, dtype=complex)
        Un = np.eye(self.D, dtype=complex)
        for _ in range(self.N - 1):
            Un = Un @ U
            acc = acc + Un
        return acc / self.N

    # --- relational observables --------------------------------------
    def O_full(self, i: int, tau: float, A: np.ndarray) -> np.ndarray:
        ket = self.clock_bra(i, tau).conj()[:, None]
        proj = ket @ ket.conj().T
        if i == 1:
            K = np.kron(proj, A)
        else:
            A4 = A.reshape(self.N, 4, self.N, 4)
            K = np.einsum("asbt,kl->aksblt", A4, proj).reshape(self.D, self.D)
        return self.N * (self.Pi @ K @ self.Pi)

    def O_red(self, i: int, tau: float, A: np.ndarray) -> np.ndarray:
        V = self.V(i, tau)
        return V.conj().T @ A @ V

    def omega(self, c: np.ndarray, i: int, tau: float, A: np.ndarray) -> complex:
        v = self.V(i, tau) @ c
        return complex(v.conj() @ A @ v)

    def random_phys(self, rng) -> np.ndarray:
        c = rng.normal(size=self.d) + 1j * rng.normal(size=self.d)
        return c / np.linalg.norm(c)

    def phys_from_kin(self, psi_kin: np.ndarray) -> np.ndarray:
        c = self.B.conj().T @ psi_kin
        return c / np.linalg.norm(c)

    def taus(self):
        return [2 * np.pi * n / self.N for n in range(self.N)]

    # --- energy ledger ---------------------------------------------------
    def ledger(self, c: np.ndarray, i: int, tau: float, HS=None, transport=None) -> dict:
        """Returns E_total, E_seen, E_unseen(formula), p_b, E_b for observer i at tau.

        transport: optional unitary Phi on C_j (x) S; projections are transported A -> Phi A Phi^dag.
        """
        HS = self.HS if HS is None else HS
        IN = self.IN
        def lift(X):
            Y = np.kron(IN, X)
            if transport is not None:
                Y = transport @ Y @ transport.conj().T
            return Y
        v = self.V(i, tau) @ c
        norm = float((v.conj() @ v).real)
        ev = lambda Y: float((v.conj() @ Y @ v).real) / norm
        E_total = ev(lift(HS))
        parts = [ev(lift(P @ HS @ P)) for P in P_REG]
        p = [ev(lift(P)) for P in P_REG]
        E_seen = sum(parts)
        E_unseen_formula = ev(lift(off_diag_part(HS)))
        E_b = [parts[b] / p[b] if p[b] > 1e-14 else float("nan") for b in range(2)]
        return {"E_total": E_total, "E_seen": E_seen, "E_unseen": E_total - E_seen,
                "E_unseen_formula": E_unseen_formula, "p": p, "E_b": E_b, "norm": norm}


def random_complex(rng, n):
    return rng.normal(size=(n, n)) + 1j * rng.normal(size=(n, n))


def main() -> int:
    checks: dict[str, dict] = {}

    def rec(name, ok, **info):
        clean = {}
        for k, v in info.items():
            if isinstance(v, (np.floating, float)):
                clean[k] = float(v)
            elif isinstance(v, (np.integer, int)):
                clean[k] = int(v)
            elif isinstance(v, (np.bool_, bool)):
                clean[k] = bool(v)
            else:
                clean[k] = v
        checks[name] = {"pass": bool(ok), **clean}

    rng = np.random.default_rng(SEED)
    E_STAR = 1.0
    HS_A0 = E_STAR * np.kron(I2, NQ)
    HS_A2 = E_STAR * np.kron(I2, NQ) + 2.0 * np.kron(SX, NQ)
    HS_B = np.kron(E_STAR * I2 + 3.0 * SX + 4.0 * SZ, NQ)
    HS_E39 = E_STAR * (np.kron(I2, NQ) + np.kron(I2 - NR, I2))

    configs = {
        "A0": Model(7, HS_A0),
        "A2": Model(7, HS_A2),
        "B": Model(13, HS_B),
    }
    rec("spectra_integer_and_within_half_N",
        all(np.max(np.abs(m.eps)) < m.N / 2 for m in configs.values()),
        eps_A0=configs["A0"].eps.tolist(), eps_A2=configs["A2"].eps.tolist(), eps_B=configs["B"].eps.tolist(),
        N_A=7, N_B=13)

    # ---------------- structural checks (S1, S2) on every config ----------------
    for name, m in configs.items():
        Pi_avg = m.Pi_group_average()
        rec(f"S1_{name}_Pi_group_average_equals_modN_kernel_projector", opnorm(Pi_avg - m.Pi) < TOL,
            residual=opnorm(Pi_avg - m.Pi), tol=TOL)
        rec(f"S1_{name}_Pi_idempotent_hermitian", opnorm(m.Pi @ m.Pi - m.Pi) < TOL and opnorm(m.Pi - m.Pi.conj().T) < TOL,
            residual=max(opnorm(m.Pi @ m.Pi - m.Pi), opnorm(m.Pi - m.Pi.conj().T)), tol=TOL)
        rec(f"S1_{name}_phys_dim_equals_4N", m.d == 4 * m.N, value=m.d, expected=4 * m.N)
        rec(f"S1_{name}_Hfull_consistent_with_lam", opnorm(m.Hfull - m.Wfull @ np.diag(m.lam.astype(complex)) @ m.Wfull.conj().T) < TOL,
            residual=opnorm(m.Hfull - m.Wfull @ np.diag(m.lam.astype(complex)) @ m.Wfull.conj().T))
        worst_u = 0.0
        for i in (1, 2):
            for tau in m.taus():
                V = m.V(i, tau)
                worst_u = max(worst_u, opnorm(V.conj().T @ V - np.eye(m.d)), opnorm(V @ V.conj().T - np.eye(4 * m.N)))
        rec(f"S2_{name}_V_i_unitary_onto_full_Cj_x_S_all_tau", worst_u < TOL, residual=worst_u, tol=TOL)
        # O_full definition vs reduced formula
        worst_o = 0.0
        for i in (1, 2):
            for tau in m.taus()[:3]:
                A = random_complex(rng, 4 * m.N)
                Of = m.O_full(i, tau, A)
                Or = m.B @ m.O_red(i, tau, A) @ m.B.conj().T
                worst_o = max(worst_o, opnorm(Of - Or))
        rec(f"S2_{name}_O_full_definition_equals_B_Vdag_A_V_Bdag", worst_o < TOL, residual=worst_o, tol=TOL)
        # homomorphism
        worst_h = 0.0
        for _ in range(N_RANDOM_OPS):
            A = random_complex(rng, 4 * m.N)
            Bm = random_complex(rng, 4 * m.N)
            i = int(rng.integers(1, 3))
            tau = m.taus()[int(rng.integers(0, m.N))]
            worst_h = max(worst_h, opnorm(m.O_red(i, tau, A @ Bm) - m.O_red(i, tau, A) @ m.O_red(i, tau, Bm)) / (1 + opnorm(A @ Bm)))
        rec(f"S2_{name}_A_to_O_A_preserves_products_20_random_AB", worst_h < TOL, max_rel_residual=worst_h, tol=TOL)
        # Schroedinger evolution of the reduced state
        worst_s = 0.0
        for _ in range(3):
            c = m.random_phys(rng)
            for i in (1, 2):
                for tau in m.taus():
                    Hj = m.HjS[i]
                    w, Q = np.linalg.eigh(Hj)
                    Ut = Q @ np.diag(np.exp(-1j * w * tau)) @ Q.conj().T
                    worst_s = max(worst_s, np.linalg.norm(m.V(i, tau) @ c - Ut @ (m.V(i, 0.0) @ c)))
        rec(f"S3_{name}_reduced_state_evolves_with_Hj_plus_HS_on_lattice", worst_s < TOL, residual=worst_s, tol=TOL)
        # Phi unitary on full space and commutes with 1 (x) H_S
        worst_p, worst_c = 0.0, 0.0
        for tau in m.taus():
            Phi = m.V(2, tau) @ m.V(1, tau).conj().T
            worst_p = max(worst_p, opnorm(Phi.conj().T @ Phi - np.eye(4 * m.N)), opnorm(Phi @ Phi.conj().T - np.eye(4 * m.N)))
            HSl = np.kron(m.IN, m.HS)
            worst_c = max(worst_c, opnorm(Phi @ HSl - HSl @ Phi))
        rec(f"S5_{name}_Phi_dag_Phi_eq_1_full_space_all_tau", worst_p < TOL, residual=worst_p, tol=TOL)
        rec(f"S5_{name}_Phi_commutes_with_1xHS", worst_c < TOL, residual=worst_c, tol=TOL)

    # ---------------- claim (1), (2): every config, 20 states, all i, tau ----------------
    states = {name: [m.random_phys(rng) for _ in range(N_STATES)] for name, m in configs.items()}
    for name, m in configs.items():
        worst1, worst_norm, worst2 = 0.0, 0.0, 0.0
        HSk = kron3(m.IN, m.IN, m.HS)
        for c in states[name]:
            psi = m.B @ c
            E_kin = float((psi.conj() @ HSk @ psi).real)
            for i in (1, 2):
                for tau in m.taus():
                    L = m.ledger(c, i, tau)
                    worst1 = max(worst1, abs(L["E_total"] - E_kin))
                    worst_norm = max(worst_norm, abs(L["norm"] - 1.0))
                    worst2 = max(worst2, abs(L["E_unseen"] - L["E_unseen_formula"]))
        rec(f"K3_1_{name}_E_total_equals_<HS>_all_i_tau_20_states", worst1 < TOL, residual=worst1, tol=TOL)
        rec(f"K3_1_{name}_omega_O_1_equals_1", worst_norm < TOL, residual=worst_norm, tol=TOL)
        rec(f"K3_2_{name}_E_unseen_equals_offdiag_formula", worst2 < TOL, residual=worst2, tol=TOL)

    # ---------------- claim (3): A0 (g=0) ----------------
    m = configs["A0"]
    worst_un, worst_led, worst_p = 0.0, 0.0, 0.0
    for c in states["A0"]:
        ref = m.ledger(c, 1, 0.0)
        for i in (1, 2):
            for tau in m.taus():
                L = m.ledger(c, i, tau)
                worst_un = max(worst_un, abs(L["E_unseen"]))
                worst_led = max(worst_led, abs(L["p"][0] * L["E_b"][0] + L["p"][1] * L["E_b"][1] - L["E_total"]))
                worst_p = max(worst_p, abs(L["p"][0] - ref["p"][0]), abs(L["p"][1] - ref["p"][1]),
                              abs(L["E_b"][0] - ref["E_b"][0]), abs(L["E_b"][1] - ref["E_b"][1]))
    rec("K3_3_A0_E_unseen_zero_all_i_tau", worst_un < TOL, residual=worst_un, tol=TOL,
        comm_Pb_HS=max(opnorm(comm(P, m.HS)) for P in P_REG))
    rec("K3_3_A0_sum_pb_Eb_equals_E_total", worst_led < TOL, residual=worst_led, tol=TOL)
    rec("K3_3_A0_pb_and_Eb_observer_and_tau_independent", worst_p < TOL, residual=worst_p, tol=TOL)
    # E39-C one-receipt: correlated register-flux state, H_S' = E*(n_Q + 1 - n_R)
    m39 = Model(7, HS_E39)
    theta = 0.7
    phi_S = np.zeros(4, dtype=complex)
    phi_S[2 * 1 + 1] = np.cos(theta)  # |r=1 (locked), q=1>
    phi_S[2 * 0 + 0] = np.sin(theta)  # |r=0 (mobile), q=0>
    psi_kin = np.kron(np.kron(m39.clock_bra(1, 0.0).conj(), m39.clock_bra(2, 0.0).conj()), phi_S)
    c39 = m39.phys_from_kin(psi_kin)
    worst39, worst39b = 0.0, 0.0
    for i in (1, 2):
        for tau in m39.taus():
            L = m39.ledger(c39, i, tau)
            worst39 = max(worst39, abs(L["p"][0] * E_STAR + L["p"][1] * E_STAR - E_STAR), abs(L["E_total"] - E_STAR),
                          abs(L["E_b"][0] - E_STAR), abs(L["E_b"][1] - E_STAR), abs(L["p"][1] - np.cos(theta) ** 2), abs(L["E_unseen"]))
            L2 = m.ledger(m.phys_from_kin(np.kron(np.kron(m.clock_bra(1, 0.0).conj(), m.clock_bra(2, 0.0).conj()), phi_S)), i, tau)
            worst39b = max(worst39b, abs(L2["E_total"] - np.cos(theta) ** 2 * E_STAR), abs(L2["E_b"][1] - E_STAR), abs(L2["E_b"][0]), abs(L2["E_unseen"]))
    rec("K3_3_E39C_one_receipt_pm_E+pL_E=E_and_E_total=E_star_all_i_tau", worst39 < TOL, residual=worst39, tol=TOL,
        p_L=float(np.cos(theta) ** 2), eps_E39=m39.eps.tolist())
    rec("K3_3_A0_correlated_state_E_total=pL_E_star_E1=E_star_E0=0", worst39b < TOL, residual=worst39b, tol=TOL)

    # ---------------- claim (4): frame dependence and transport covariance ----------------
    def frame_dependence(m, cs):
        diffs = []
        tau_var = []
        for c in cs:
            vals = {i: [m.ledger(c, i, tau)["E_unseen"] for tau in m.taus()] for i in (1, 2)}
            diffs.append(max(abs(a - b) for a, b in zip(vals[1], vals[2])))
            tau_var.append(max(vals[1]) - min(vals[1]))
        return diffs, tau_var

    # literal task H_S (A2): sigma_x only -> D(H_S)=E* n_Q commutes with H_S -> no frame dependence possible
    m = configs["A2"]
    diffsA2, tvA2 = frame_dependence(m, states["A2"])
    rec("NEG_A2_literal_sigma_x_only_E_unseen_frame_independent_because_[D(HS),HS]=0",
        max(diffsA2) < TOL and opnorm(comm(block_diag_part(m.HS), m.HS)) < TOL and max(opnorm(comm(P, m.HS)) for P in P_REG) > SEP,
        max_diff_obs1_obs2=max(diffsA2), max_tau_variation=max(tvA2), tol=TOL,
        comm_D_HS=opnorm(comm(block_diag_part(m.HS), m.HS)), comm_Pb_HS=max(opnorm(comm(P, m.HS)) for P in P_REG),
        note="task-literal claim (4a) is false for this H_S; sharpened criterion [D(H_S),H_S]!=0 needed")
    # config B
    m = configs["B"]
    diffsB, tvB = frame_dependence(m, states["B"])
    n_dep = int(sum(d > SEP for d in diffsB))
    rec("K3_4a_B_E_unseen_frame_dependent_exists", n_dep >= 1, n_states_with_diff_gt_sep=n_dep, max_diff=max(diffsB), min_diff=min(diffsB), sep=SEP,
        comm_D_HS=opnorm(comm(block_diag_part(m.HS), m.HS)), max_tau_variation_obs1=max(tvB))
    # explicit two-level state: Psi = a|k1,k2,e> + b|k1',k2,e'>, e,e' the n_Q=1 eigenvectors (eps 6, -4)
    e_hi = int(np.argmax(m.eps)); e_lo = int(np.argmin(m.eps))
    k2 = 5
    def phys_col(k1, k2, e):
        idx = (k1 * m.N + k2) * 4 + e
        col = np.where(np.where(m.mask)[0] == idx)[0]
        return int(col[0])
    k1 = int((-k2 - m.eps[e_hi]) % m.N); k1p = int((-k2 - m.eps[e_lo]) % m.N)
    a, b = 0.6 + 0.3j, np.sqrt(1 - abs(0.6 + 0.3j) ** 2)
    c2 = np.zeros(m.d, dtype=complex); c2[phys_col(k1, k2, e_hi)] = a; c2[phys_col(k1p, k2, e_lo)] = b
    Dm = m.W.conj().T @ block_diag_part(m.HS) @ m.W
    predicted = 2 * (np.conj(a) * b * Dm[e_hi, e_lo]).real
    L1 = m.ledger(c2, 1, 0.0); L2 = m.ledger(c2, 2, 0.0)
    rec("K3_4a_B_two_level_state_E_seen_diff_equals_2Re(conj(a)b D_ee')",
        abs((L1["E_seen"] - L2["E_seen"]) - predicted) < TOL and abs(predicted) > SEP and k1 != k1p,
        observed=L1["E_seen"] - L2["E_seen"], predicted=predicted, k1=k1, k1p=k1p, D_ee=complex(Dm[e_hi, e_lo]).real, tol=TOL)
    # transport covariance: observer 2 with Phi_12 P_b Phi_12^dag reproduces observer 1 exactly
    worst_tr, worst_id = 0.0, 0.0
    for c in states["B"]:
        for tau in m.taus():
            Phi = m.V(2, tau) @ m.V(1, tau).conj().T
            L1 = m.ledger(c, 1, tau)
            L2t = m.ledger(c, 2, tau, transport=Phi)
            worst_tr = max(worst_tr, abs(L1["E_unseen"] - L2t["E_unseen"]), abs(L1["E_seen"] - L2t["E_seen"]),
                           abs(L1["p"][0] - L2t["p"][0]), abs(L1["E_b"][1] - L2t["E_b"][1]))
            L2i = m.ledger(c, 2, tau, transport=np.eye(4 * m.N, dtype=complex))
            worst_id = max(worst_id, abs(L1["E_unseen"] - L2i["E_unseen"]))
    rec("K3_4b_B_transported_projections_reproduce_observer1_ledger_exactly", worst_tr < TOL, residual=worst_tr, tol=TOL)
    rec("NEG_B_identity_transport_fails", worst_id > SEP, residual=worst_id, sep=SEP)
    # transport with different tau_1 != tau_2 (informational + check)
    worst_tr2 = 0.0
    for c in states["B"][:5]:
        t1, t2 = m.taus()[3], m.taus()[8]
        Phi = m.V(2, t2) @ m.V(1, t1).conj().T
        worst_tr2 = max(worst_tr2, abs(m.ledger(c, 1, t1)["E_unseen"] - m.ledger(c, 2, t2, transport=Phi)["E_unseen"]))
    rec("K3_4b_B_transport_covariance_tau1_ne_tau2", worst_tr2 < TOL, residual=worst_tr2, tol=TOL)

    # ---------------- claim (5): winding accounting ----------------
    for name in ("A2", "B"):
        m = configs[name]
        N = m.N
        c = states[name][0]
        base = m.ledger(c, 1, 0.0)["E_total"]
        results = {}
        ok = True
        for mm in (1, -2):
            HSs = m.HS + N * mm * I4
            ms = Model(N, HSs)
            same_Pi = opnorm(ms.Pi - m.Pi)
            cs = ms.phys_from_kin(m.B @ c)
            shift = ms.ledger(cs, 1, 0.0)["E_total"] - base
            ok = ok and same_Pi < TOL and abs(shift - N * mm) < TOL
            results[f"uniform_m={mm}"] = {"Pi_residual": same_Pi, "shift": shift, "expected": N * mm}
        rec(f"K3_5_{name}_uniform_representative_shift_moves_E_total_by_exactly_N_m", ok, tol=TOL, **{k: v for k, v in results.items()})
        # non-uniform: shift a single eigenvalue by N
        e_hi = int(np.argmax(m.eps))
        Pe = m.W[:, [e_hi]] @ m.W[:, [e_hi]].conj().T
        HSn = m.HS + N * Pe
        mn = Model(N, HSn)
        same_Pi = opnorm(mn.Pi - m.Pi)
        shifts = []
        for c in states[name][:5]:
            cs = mn.phys_from_kin(m.B @ c)
            vv = m.V(1, 0.0) @ c
            pe = float(complex(vv.conj() @ np.kron(m.IN, Pe) @ vv).real)
            shifts.append((mn.ledger(cs, 1, 0.0)["E_total"] - m.ledger(c, 1, 0.0)["E_total"], N * pe))
        exact_acc = max(abs(s - t) for s, t in shifts)
        frac = [abs((s / N) - round(s / N)) for s, _ in shifts]
        rec(f"K3_5_{name}_single_eigenvalue_shift_Pi_unchanged_and_dE=N<P_e>", same_Pi < TOL and exact_acc < TOL,
            Pi_residual=same_Pi, accounting_residual=exact_acc, tol=TOL,
            shift_over_N_fractional_parts=[float(f) for f in frac],
            is_integer_multiple_of_N_for_random_states=bool(max(frac) < TOL),
            note="literal (5) 'integer multiple of N' holds only for uniform shifts or H_S eigenstates; exact rule is dE_total = N<K>_Psi")
        # clock representative shift: H_1 -> H_1 + N. Pi and E_total unchanged; the kinematic H restricted to
        # H_phys has spectrum in N*Z (winding number operator W := H/N), and the shift moves W by exactly +1.
        c0 = states[name][0]
        mc = Model(N, m.HS, clock_shift=(N, 0))
        cs = mc.phys_from_kin(m.B @ c0)
        Hred = m.B.conj().T @ m.Hfull @ m.B
        Hred_shift = mc.B.conj().T @ mc.Hfull @ mc.B
        wind = np.linalg.eigvalsh((Hred + Hred.conj().T) / 2) / N
        rec(f"K3_5_{name}_clock_representative_shift_leaves_Pi_and_E_total_and_moves_winding_by_1",
            opnorm(mc.Pi - m.Pi) < TOL and abs(mc.ledger(cs, 1, 0.0)["E_total"] - base) < TOL
            and opnorm(Hred_shift - Hred - N * np.eye(m.d)) < TOL and np.max(np.abs(wind - np.round(wind))) < TOL and np.max(np.abs(wind)) > 0.5,
            Pi_residual=opnorm(mc.Pi - m.Pi), dE=mc.ledger(cs, 1, 0.0)["E_total"] - base,
            winding_spectrum=sorted(set(int(round(w)) for w in wind)), shift_residual=opnorm(Hred_shift - Hred - N * np.eye(m.d)), tol=TOL,
            note="H_phys = ker(H mod N), not ker H: H|Psi> = N W |Psi> with integer W; the constraint fixes total energy only mod N")

    # ---------------- exact-kernel comparison (attempt-01 style) ----------------
    mx = Model(7, HS_A2, mode="exact")
    rec("X_exact_kernel_phys_dim", mx.d == 24, value=mx.d, expected=24, modN_dim=configs["A2"].d)
    worst_hx = float("inf"); worst_hx_max = 0.0
    for _ in range(N_RANDOM_OPS):
        A = random_complex(rng, 4 * mx.N); Bm = random_complex(rng, 4 * mx.N)
        r = opnorm(mx.O_red(1, 0.0, A @ Bm) - mx.O_red(1, 0.0, A) @ mx.O_red(1, 0.0, Bm)) / (1 + opnorm(A @ Bm))
        worst_hx = min(worst_hx, r); worst_hx_max = max(worst_hx_max, r)
    rec("X_exact_kernel_A_to_O_A_fails_products_20_random_AB", worst_hx > SEP, min_rel_residual=worst_hx, max_rel_residual=worst_hx_max, sep=SEP)
    Phix = mx.V(2, 0.0) @ mx.V(1, 0.0).conj().T
    rec("X_exact_kernel_Phi_dag_Phi_ne_1", opnorm(Phix.conj().T @ Phix - np.eye(4 * mx.N)) > SEP, residual=opnorm(Phix.conj().T @ Phix - np.eye(4 * mx.N)),
        rank_Phi=int(np.linalg.matrix_rank(Phix)), full_dim=4 * mx.N)
    # boundary annihilation: norms of Phi on energy-basis kets
    Wl = np.kron(mx.IN, mx.W)
    norms_x = np.linalg.norm(Phix @ Wl, axis=0)
    PhiN = configs["A2"].V(2, 0.0) @ configs["A2"].V(1, 0.0).conj().T
    norms_n = np.linalg.norm(PhiN @ np.kron(configs["A2"].IN, configs["A2"].W), axis=0)
    rec("X_boundary_annihilation_exact_vs_modN", float(norms_x.min()) < TOL and abs(norms_n.min() - 1) < TOL and abs(norms_n.max() - 1) < TOL,
        exact_min_norm=float(norms_x.min()), exact_n_annihilated=int((norms_x < TOL).sum()), modN_min_norm=float(norms_n.min()), modN_max_norm=float(norms_n.max()))
    # E_total still fine in exact kernel (claim (1) does not depend on the kernel choice)
    worst_x1 = 0.0
    HSk = kron3(mx.IN, mx.IN, mx.HS)
    for _ in range(5):
        c = mx.random_phys(rng); psi = mx.B @ c
        Ek = float((psi.conj() @ HSk @ psi).real)
        for i in (1, 2):
            for tau in mx.taus():
                worst_x1 = max(worst_x1, abs(mx.ledger(c, i, tau)["E_total"] - Ek))
    rec("X_exact_kernel_claim1_still_holds", worst_x1 < TOL, residual=worst_x1, tol=TOL)

    all_pass = all(v["pass"] for v in checks.values())
    out = {"claim": "K3", "question": "Q-0002", "attempt": 2, "seed": SEED, "tol": TOL, "sep": SEP,
           "n_states": N_STATES, "configs": {"A0": "N=7,E*=1,g=0", "A2": "N=7,E*=1,g=2 sigma_x (task-literal)",
                                             "B": "N=13,E*=1,(g,h)=(3,4)", "E39": "N=7,H_S'=E*(n_Q+1-n_R)", "X": "exact kernel N=7 with A2 H_S"},
           "checks": checks, "all_pass": all_pass}
    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, "result.json"), "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2, ensure_ascii=False)
    print(json.dumps(out, ensure_ascii=False))
    return 0 if all_pass else 1


if __name__ == "__main__":
    sys.exit(main())
