'''Finite-time E68 scalar contact plus rotating s-channel exchange witness.

The declared state is |2_k,a>.  The retained intermediate states are the two
|1_2k,c> states generated by the rotating cubic monomial b_c^dagger a_a a_a
and its Hermitian conjugate.  This is second-order closed for the survival
amplitude, but it is not the complete normally ordered cubic Fock space.
'''

from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass

import numpy as np

from examples.physics.qft_reference_flrw_background import (
    ReferenceFlrwParameters,
    ReferenceFlrwState,
)
from examples.physics.qft_reference_flrw_cubic_dynamics import (
    dynamic_reduced_scalar_cubic_tensor_pair,
    scalar_interaction_hamiltonian_cubic_tensor_pair,
)
from examples.physics.qft_reference_flrw_cubic_dyson import (
    finite_time_exponential_kernel,
)
from examples.physics.qft_reference_flrw_cubic_exchange import (
    ResonanceCertificate,
    evaluate_scalar_cubic_exchange_gate,
    scalar_cubic_exchange_channels,
)
from examples.physics.qft_reference_flrw_quartic_contact import (
    evaluate_scalar_quartic_contact_gate,
)


def _first_moment_exponential_kernel(
    frequency_bar: float,
    interval_bar: float,
) -> complex:
    '''Return integral_0^T t exp(i omega t) dt with a stable zero limit.'''

    omega = float(frequency_bar)
    interval = float(interval_bar)
    argument = omega * interval
    if abs(argument) <= 1.0e-4:
        total = 0.0j
        factorial = 1.0
        power = 1.0 + 0.0j
        for order in range(12):
            if order > 0:
                factorial *= order
                power *= 1j * omega
            total += power * interval ** (order + 2) / (
                factorial * (order + 2)
            )
        return complex(total)
    return complex(
        (np.exp(1j * argument) * (1.0 - 1j * argument) - 1.0)
        / omega**2
    )


def finite_time_ordered_double_kernel(
    later_frequency_bar: float,
    earlier_frequency_bar: float,
    interval_bar: float,
) -> complex:
    '''Return integral_0^T dt2 e^(i x t2) integral_0^t2 dt1 e^(i y t1).'''

    later = float(later_frequency_bar)
    earlier = float(earlier_frequency_bar)
    interval = float(interval_bar)
    if (
        not np.isfinite(later)
        or not np.isfinite(earlier)
        or not np.isfinite(interval)
        or interval <= 0.0
    ):
        raise ValueError('the ordered kernel requires finite frequencies and T>0')
    if abs(earlier * interval) <= 1.0e-7:
        return _first_moment_exponential_kernel(later, interval)
    return complex(
        (
            finite_time_exponential_kernel(later + earlier, interval)
            - finite_time_exponential_kernel(later, interval)
        )
        / (1j * earlier)
    )


def simpson_ordered_double_kernel(
    later_frequency_bar: float,
    earlier_frequency_bar: float,
    interval_bar: float,
    *,
    subintervals: int,
    block_rows: int = 256,
) -> complex:
    '''Independently integrate the ordered triangle via a unit-square map.'''

    if (
        not isinstance(subintervals, int)
        or subintervals < 2
        or subintervals % 2
    ):
        raise ValueError('the ordered Simpson grid must be a positive even integer')
    if not isinstance(block_rows, int) or block_rows < 1:
        raise ValueError('the ordered Simpson block size must be positive')
    interval = float(interval_bar)
    if not np.isfinite(interval) or interval <= 0.0:
        raise ValueError('the ordered Simpson interval must be positive')
    count = subintervals
    unit = np.linspace(0.0, 1.0, count + 1)
    weights = np.ones(count + 1)
    weights[1:-1:2] = 4.0
    weights[2:-1:2] = 2.0
    inner_scale = 1.0 / (3.0 * count)
    outer_total = 0.0j
    for start in range(0, count + 1, block_rows):
        stop = min(count + 1, start + block_rows)
        outer = unit[start:stop]
        phases = np.exp(
            1j
            * float(later_frequency_bar)
            * interval
            * outer[:, None]
            + 1j
            * float(earlier_frequency_bar)
            * interval
            * outer[:, None]
            * unit[None, :]
        )
        inner = inner_scale * (phases @ weights)
        outer_total += np.sum(
            weights[start:stop] * interval**2 * outer * inner
        )
    return complex(outer_total / (3.0 * count))


def simpson_time_ordered_square_kernel(
    later_frequency_bar: float,
    earlier_frequency_bar: float,
    interval_bar: float,
    *,
    subintervals: int,
    block_rows: int = 256,
) -> complex:
    '''Return a Richardson-improved direct two-theta square integral.'''

    if (
        not isinstance(subintervals, int)
        or subintervals < 2
        or subintervals % 2
    ):
        raise ValueError('the square Simpson grid must be a positive even integer')
    if not isinstance(block_rows, int) or block_rows < 1:
        raise ValueError('the square Simpson block size must be positive')
    interval = float(interval_bar)
    if not np.isfinite(interval) or interval <= 0.0:
        raise ValueError('the square Simpson interval must be positive')

    def direct_square(count: int) -> complex:
        unit = np.linspace(0.0, 1.0, count + 1)
        weights = np.ones(count + 1)
        weights[1:-1:2] = 4.0
        weights[2:-1:2] = 2.0
        total = 0.0j
        for start in range(0, count + 1, block_rows):
            stop = min(count + 1, start + block_rows)
            first = unit[start:stop, None]
            second = unit[None, :]
            first_is_later = first >= second
            phase = np.where(
                first_is_later,
                np.exp(
                    1j
                    * interval
                    * (
                        float(later_frequency_bar) * first
                        + float(earlier_frequency_bar) * second
                    )
                ),
                np.exp(
                    1j
                    * interval
                    * (
                        float(later_frequency_bar) * second
                        + float(earlier_frequency_bar) * first
                    )
                ),
            )
            total += np.sum(
                weights[start:stop, None] * weights[None, :] * phase
            )
        return complex(0.5 * interval**2 * total / (9.0 * count**2))

    coarse = direct_square(subintervals)
    fine = direct_square(2 * subintervals)
    # The theta-boundary derivative kink leaves an O(h^2) diagonal error.
    return complex((4.0 * fine - coarse) / 3.0)


def simpson_time_ordered_square_kernel_with_stability(
    later_frequency_bar: float,
    earlier_frequency_bar: float,
    interval_bar: float,
    *,
    subintervals: int,
    block_rows: int = 256,
) -> tuple[complex, float]:
    '''Return the refined square result and its N-to-2N stability.'''

    first = simpson_time_ordered_square_kernel(
        later_frequency_bar,
        earlier_frequency_bar,
        interval_bar,
        subintervals=subintervals,
        block_rows=block_rows,
    )
    second = simpson_time_ordered_square_kernel(
        later_frequency_bar,
        earlier_frequency_bar,
        interval_bar,
        subintervals=2 * subintervals,
        block_rows=block_rows,
    )
    return complex(second), float(abs(second - first))


def select_certified_resonant_matrix_element(
    key: tuple[int, int, int],
    raw_matrix_element: complex,
    certificates: Mapping[tuple[int, int, int], ResonanceCertificate],
    *,
    relative_tolerance: float = 1.0e-10,
    absolute_tolerance: float = 1.0e-12,
) -> complex:
    '''Apply only a matching, branch-keyed resonance disposition.'''

    certificate = certificates.get(key)
    if certificate is None:
        raise ValueError(f'missing resonance certificate for channel {key}')
    if not np.isclose(
        raw_matrix_element,
        certificate.production_matrix_element,
        rtol=relative_tolerance,
        atol=absolute_tolerance,
    ):
        raise ValueError(
            f'resonance certificate does not match channel {key} matrix element'
        )
    if certificate.disposition == 'null':
        return 0.0j
    if (
        certificate.disposition == 'resolved'
        and certificate.local_exchange_elimination_rejected
    ):
        return complex(raw_matrix_element)
    raise ValueError(f'unclassified resonant channel {key}')


def _exact_star_survival_amplitude(
    initial_energy: float,
    intermediate_energies: tuple[float, ...],
    matrix_elements: tuple[complex, ...],
    contact: float,
    interval_bar: float,
    coupling: float,
) -> tuple[complex, float]:
    '''Return the interaction-picture survival amplitude of the Hermitian star.'''

    dimension = 1 + len(intermediate_energies)
    hamiltonian = np.zeros((dimension, dimension), dtype=complex)
    hamiltonian[0, 0] = initial_energy + coupling**2 * contact
    for index, (energy, matrix_element) in enumerate(
        zip(intermediate_energies, matrix_elements, strict=True),
        start=1,
    ):
        hamiltonian[index, index] = energy
        hamiltonian[index, 0] = coupling * matrix_element
        hamiltonian[0, index] = coupling * matrix_element.conjugate()
    hermiticity = float(np.linalg.norm(hamiltonian - hamiltonian.conj().T))
    eigenvalues, eigenvectors = np.linalg.eigh(hamiltonian)
    evolution = (
        eigenvectors
        @ np.diag(np.exp(-1j * eigenvalues * interval_bar))
        @ eigenvectors.conj().T
    )
    interaction = np.exp(1j * initial_energy * interval_bar) * evolution[0, 0]
    return complex(interaction), hermiticity


@dataclass(frozen=True)
class ScalarQuarticExchangeBranch:
    branch: int
    intermediate_channel_keys: tuple[tuple[int, int, int], ...]
    intermediate_resonance_dispositions: tuple[str, ...]
    intermediate_raw_matrix_element_magnitudes: tuple[float, ...]
    contact_matrix_element: float
    intermediate_matrix_element_magnitudes: tuple[float, float]
    energy_mismatches_bar: tuple[float, float]
    resonant_null_channel_count: int
    discarded_raw_resonant_magnitude: float
    contact_coefficient_real: float
    contact_coefficient_imag: float
    exchange_coefficient_real: float
    exchange_coefficient_imag: float
    total_coefficient_real: float
    total_coefficient_imag: float
    finest_exact_normalized_error: float
    lambda_quarter_scaling_residual: float
    wrong_contact_sign_negative_control: float
    omitted_intermediate_negative_control: float
    omitted_ordering_negative_control: float
    wrong_repeated_leg_negative_control: float


@dataclass(frozen=True)
class ScalarQuarticExchangeReceipt:
    base_wavenumber_bar: float
    branches: tuple[ScalarQuarticExchangeBranch, ...]
    maximum_cubic_step_residual: float
    maximum_cubic_grid_residual: float
    maximum_cubic_gauge_residual: float
    maximum_kernel_quadrature_residual: float
    maximum_kernel_grid_refinement: float
    maximum_time_ordered_square_residual: float
    maximum_time_ordered_square_grid_refinement: float
    maximum_hermiticity_residual: float
    maximum_fock_matrix_element_residual: float
    maximum_finest_exact_normalized_error: float
    maximum_lambda_quarter_scaling_residual: float
    minimum_negative_control_to_numerical_error_ratio: float
    quartic_contact_gate_passed: bool
    cubic_resonance_classification_gate_passed: bool
    declared_rotating_exchange_gate_passed: bool


def evaluate_scalar_quartic_exchange_gate(
    state: ReferenceFlrwState,
    parameters: ReferenceFlrwParameters,
    *,
    base_wavenumber_bar: float,
    interval_bar: float = 0.5,
    cubic_steps: tuple[float, float] = (5.0e-3, 2.5e-3),
    phase_points: int = 256,
    grid_phase_points: int = 512,
    simpson_subintervals: tuple[int, int] = (2048, 4096),
    square_subintervals: int = 512,
    couplings: tuple[float, float, float] = (1.0, 0.5, 0.25),
) -> ScalarQuarticExchangeReceipt:
    '''Compare H4 contact plus rotating H3 exchange with an exact star.'''

    if not np.allclose(
        np.asarray(cubic_steps[1:]),
        0.5 * np.asarray(cubic_steps[:-1]),
        rtol=0.0,
        atol=1.0e-15,
    ):
        raise ValueError('the cubic exchange steps must be successive halvings')
    if simpson_subintervals[1] != 2 * simpson_subintervals[0]:
        raise ValueError('the ordered Simpson grids must differ by a factor two')
    if not np.allclose(
        np.asarray(couplings[1:]),
        0.5 * np.asarray(couplings[:-1]),
        rtol=0.0,
        atol=1.0e-15,
    ):
        raise ValueError('the star couplings must be successive halvings')

    contact_receipt = evaluate_scalar_quartic_contact_gate(
        state,
        parameters,
        base_wavenumber_bar=base_wavenumber_bar,
        phase_points=phase_points,
        grid_phase_points=grid_phase_points,
    )
    resonance_receipt = evaluate_scalar_cubic_exchange_gate(
        state,
        parameters,
        base_wavenumber_bar=base_wavenumber_bar,
        phase_points=phase_points,
        grid_phase_points=grid_phase_points,
        interval_bar=interval_bar,
    )
    certificate_lookup = {
        item.key: item for item in resonance_receipt.resonance_certificates
    }
    if len(certificate_lookup) != len(
        resonance_receipt.resonance_certificates
    ):
        raise ValueError('resonance certificate keys must be unique')
    lagrangian_pairs = tuple(
        dynamic_reduced_scalar_cubic_tensor_pair(
            state,
            parameters,
            base_wavenumber_bar=base_wavenumber_bar,
            epsilon=step,
            phase_points=phase_points,
        )
        for step in cubic_steps
    )
    hamiltonian_pairs = tuple(
        scalar_interaction_hamiltonian_cubic_tensor_pair(
            state,
            parameters,
            base_wavenumber_bar=base_wavenumber_bar,
            flat_lagrangian_tensor=pair[0],
            unitary_lagrangian_tensor=pair[1],
        )
        for pair in lagrangian_pairs
    )
    grid_lagrangian = dynamic_reduced_scalar_cubic_tensor_pair(
        state,
        parameters,
        base_wavenumber_bar=base_wavenumber_bar,
        epsilon=cubic_steps[-1],
        phase_points=grid_phase_points,
    )
    grid_hamiltonian = scalar_interaction_hamiltonian_cubic_tensor_pair(
        state,
        parameters,
        base_wavenumber_bar=base_wavenumber_bar,
        flat_lagrangian_tensor=grid_lagrangian[0],
        unitary_lagrangian_tensor=grid_lagrangian[1],
    )
    channel_sets = tuple(
        scalar_cubic_exchange_channels(
            state,
            parameters,
            base_wavenumber_bar=base_wavenumber_bar,
            hamiltonian_tensor=pair[0],
            interval_bar=interval_bar,
        )
        for pair in hamiltonian_pairs
    )
    unitary = scalar_cubic_exchange_channels(
        state,
        parameters,
        base_wavenumber_bar=base_wavenumber_bar,
        hamiltonian_tensor=hamiltonian_pairs[-1][1],
        interval_bar=interval_bar,
    )
    grid = scalar_cubic_exchange_channels(
        state,
        parameters,
        base_wavenumber_bar=base_wavenumber_bar,
        hamiltonian_tensor=grid_hamiltonian[0],
        interval_bar=interval_bar,
    )

    def lookup(channels):
        return {
            (item.first_branch, item.second_branch, item.third_branch): item
            for item in channels
        }

    coarse_lookup, fine_lookup = tuple(lookup(items) for items in channel_sets)
    unitary_lookup = lookup(unitary)
    grid_lookup = lookup(grid)
    maximum_step = 0.0
    maximum_grid = 0.0
    maximum_gauge = 0.0
    maximum_kernel = 0.0
    maximum_kernel_grid = 0.0
    maximum_square = 0.0
    maximum_square_grid = 0.0
    maximum_hermiticity = 0.0
    maximum_fock = 0.0
    maximum_exact_error = 0.0
    maximum_scaling = 0.0
    minimum_control_ratio = np.inf
    branch_receipts = []
    for initial_branch, contact_branch in enumerate(contact_receipt.branches):
        initial_energy = 2.0 * contact_branch.frequency_bar
        energies = []
        matrix_elements = []
        raw_matrix_element_magnitudes = []
        channel_keys = []
        resonance_dispositions = []
        gaps = []
        raw_resonant = 0.0
        resonant_count = 0
        exchange_terms = []
        local_kernel_residual = 0.0
        local_kernel_grid = 0.0
        local_square_residual = 0.0
        local_square_grid = 0.0
        local_vertex_step = 0.0
        local_vertex_grid = 0.0
        local_vertex_gauge = 0.0
        for third_branch in range(2):
            key = (initial_branch, initial_branch, third_branch)
            item = fine_lookup[key]
            local_vertex_step = max(
                local_vertex_step,
                abs(item.matrix_element - coarse_lookup[key].matrix_element),
            )
            local_vertex_grid = max(
                local_vertex_grid,
                abs(item.matrix_element - grid_lookup[key].matrix_element),
            )
            local_vertex_gauge = max(
                local_vertex_gauge,
                abs(item.matrix_element - unitary_lookup[key].matrix_element),
            )
            matrix_element = item.matrix_element
            raw_matrix_element_magnitudes.append(float(abs(matrix_element)))
            channel_keys.append(key)
            if item.resonant:
                raw_resonant = max(raw_resonant, abs(matrix_element))
                certificate = certificate_lookup.get(key)
                matrix_element = select_certified_resonant_matrix_element(
                    key,
                    matrix_element,
                    certificate_lookup,
                )
                if certificate is None:
                    raise RuntimeError('certificate selection lost its key')
                resonance_dispositions.append(certificate.disposition)
                if certificate.disposition == 'null':
                    resonant_count += 1
            else:
                resonance_dispositions.append('nonresonant')
            intermediate_energy = initial_energy - item.energy_mismatch_bar
            gap = item.energy_mismatch_bar
            kernel = finite_time_ordered_double_kernel(
                gap,
                -gap,
                interval_bar,
            )
            coarse_kernel = simpson_ordered_double_kernel(
                gap,
                -gap,
                interval_bar,
                subintervals=simpson_subintervals[0],
            )
            fine_kernel = simpson_ordered_double_kernel(
                gap,
                -gap,
                interval_bar,
                subintervals=simpson_subintervals[1],
            )
            square_kernel, square_grid = (
                simpson_time_ordered_square_kernel_with_stability(
                gap,
                -gap,
                interval_bar,
                subintervals=square_subintervals,
                )
            )
            local_kernel_residual = max(
                local_kernel_residual,
                abs(kernel - fine_kernel),
            )
            local_kernel_grid = max(
                local_kernel_grid,
                abs(fine_kernel - coarse_kernel),
            )
            local_square_residual = max(
                local_square_residual,
                abs(kernel - square_kernel),
            )
            local_square_grid = max(local_square_grid, square_grid)
            energies.append(float(intermediate_energy))
            matrix_elements.append(complex(matrix_element))
            gaps.append(float(gap))
            exchange_terms.append(-abs(matrix_element) ** 2 * kernel)

        contact = float(contact_branch.flat_analytic_contact)
        contact_coefficient = -1j * contact * interval_bar
        exchange_coefficient = sum(exchange_terms, 0.0j)
        total_coefficient = contact_coefficient + exchange_coefficient
        exact_errors = []
        hermiticity = 0.0
        for coupling in couplings:
            exact, local_hermiticity = _exact_star_survival_amplitude(
                initial_energy,
                tuple(energies),
                tuple(matrix_elements),
                contact,
                interval_bar,
                coupling,
            )
            hermiticity = max(hermiticity, local_hermiticity)
            exact_errors.append(
                abs((exact - 1.0) / coupling**2 - total_coefficient)
            )
        scaling = max(
            abs(exact_errors[1] / max(exact_errors[0], 1.0e-300) - 0.25),
            abs(exact_errors[2] / max(exact_errors[1], 1.0e-300) - 0.25),
        )
        omitted_intermediate = max(
            (abs(value) for value in exchange_terms),
            default=0.0,
        )
        omitted_ordering = 0.5 * abs(exchange_coefficient)
        wrong_repeated = abs(exchange_coefficient)
        contact_numerical_error = interval_bar * max(
            contact_receipt.maximum_step_residual,
            contact_receipt.maximum_grid_residual,
            contact_receipt.maximum_gauge_residual,
            contact_receipt.maximum_analytic_direct_relative_residual
            * abs(contact),
        )
        cubic_scale = max(
            (abs(value) for value in matrix_elements),
            default=0.0,
        )
        exchange_numerical_error = interval_bar**2 * cubic_scale * max(
            local_vertex_step,
            local_vertex_grid,
            local_vertex_gauge,
        )
        numerical_error = max(
            contact_numerical_error,
            exchange_numerical_error,
            local_kernel_residual
            * sum(abs(value) ** 2 for value in matrix_elements),
            1.0e-30,
        )
        controls = (
            2.0 * abs(contact_coefficient),
            omitted_intermediate,
            omitted_ordering,
            wrong_repeated,
        )
        minimum_control_ratio = min(
            minimum_control_ratio,
            *(control / numerical_error for control in controls if control > 0.0),
        )
        maximum_step = max(maximum_step, local_vertex_step)
        maximum_grid = max(maximum_grid, local_vertex_grid)
        maximum_gauge = max(maximum_gauge, local_vertex_gauge)
        maximum_kernel = max(maximum_kernel, local_kernel_residual)
        maximum_kernel_grid = max(maximum_kernel_grid, local_kernel_grid)
        maximum_square = max(maximum_square, local_square_residual)
        maximum_square_grid = max(maximum_square_grid, local_square_grid)
        maximum_hermiticity = max(maximum_hermiticity, hermiticity)
        maximum_fock = max(
            maximum_fock,
            *(
                abs(
                    0.5 * fine_lookup[(initial_branch, initial_branch, third)].raw_vertex
                    * np.sqrt(2.0)
                    - fine_lookup[(initial_branch, initial_branch, third)].matrix_element
                )
                for third in range(2)
            ),
        )
        maximum_exact_error = max(maximum_exact_error, exact_errors[-1])
        maximum_scaling = max(maximum_scaling, scaling)
        branch_receipts.append(
            ScalarQuarticExchangeBranch(
                branch=initial_branch,
                intermediate_channel_keys=tuple(channel_keys),
                intermediate_resonance_dispositions=tuple(
                    resonance_dispositions
                ),
                intermediate_raw_matrix_element_magnitudes=tuple(
                    raw_matrix_element_magnitudes
                ),
                contact_matrix_element=contact,
                intermediate_matrix_element_magnitudes=tuple(
                    float(abs(value)) for value in matrix_elements
                ),
                energy_mismatches_bar=tuple(gaps),
                resonant_null_channel_count=resonant_count,
                discarded_raw_resonant_magnitude=float(raw_resonant),
                contact_coefficient_real=float(contact_coefficient.real),
                contact_coefficient_imag=float(contact_coefficient.imag),
                exchange_coefficient_real=float(exchange_coefficient.real),
                exchange_coefficient_imag=float(exchange_coefficient.imag),
                total_coefficient_real=float(total_coefficient.real),
                total_coefficient_imag=float(total_coefficient.imag),
                finest_exact_normalized_error=float(exact_errors[-1]),
                lambda_quarter_scaling_residual=float(scaling),
                wrong_contact_sign_negative_control=float(
                    2.0 * abs(contact_coefficient)
                ),
                omitted_intermediate_negative_control=float(
                    omitted_intermediate
                ),
                omitted_ordering_negative_control=float(omitted_ordering),
                wrong_repeated_leg_negative_control=float(wrong_repeated),
            )
        )
    passed = bool(
        contact_receipt.declared_quartic_contact_gate_passed
        and resonance_receipt.declared_exchange_gate_passed
        and maximum_step < 2.0e-4
        and maximum_grid < 1.0e-8
        and maximum_gauge < 1.0e-6
        and maximum_kernel < 1.0e-10
        and maximum_kernel_grid < 1.0e-10
        and maximum_square < 1.0e-10
        and maximum_square_grid < 1.0e-10
        and maximum_hermiticity < 1.0e-12
        and maximum_fock < 1.0e-12
        and maximum_exact_error < 1.0e-4
        and maximum_scaling < 0.1
        and minimum_control_ratio > 10.0
    )
    return ScalarQuarticExchangeReceipt(
        base_wavenumber_bar=float(base_wavenumber_bar),
        branches=tuple(branch_receipts),
        maximum_cubic_step_residual=float(maximum_step),
        maximum_cubic_grid_residual=float(maximum_grid),
        maximum_cubic_gauge_residual=float(maximum_gauge),
        maximum_kernel_quadrature_residual=float(maximum_kernel),
        maximum_kernel_grid_refinement=float(maximum_kernel_grid),
        maximum_time_ordered_square_residual=float(maximum_square),
        maximum_time_ordered_square_grid_refinement=float(
            maximum_square_grid
        ),
        maximum_hermiticity_residual=float(maximum_hermiticity),
        maximum_fock_matrix_element_residual=float(maximum_fock),
        maximum_finest_exact_normalized_error=float(maximum_exact_error),
        maximum_lambda_quarter_scaling_residual=float(maximum_scaling),
        minimum_negative_control_to_numerical_error_ratio=float(
            minimum_control_ratio
        ),
        quartic_contact_gate_passed=(
            contact_receipt.declared_quartic_contact_gate_passed
        ),
        cubic_resonance_classification_gate_passed=(
            resonance_receipt.declared_exchange_gate_passed
        ),
        declared_rotating_exchange_gate_passed=passed,
    )
